// AUTO-GENERATED by scripts/write-render-version.mjs — do not edit manually.
// Cambia automaticamente quando i file di rendering (badges, blur, logo, font,
// route poster) cambiano: invalida cache server e URL Stremio senza bump manuali.
export const RENDER_VERSION = "3f131b47e5"
export const POSTER_URL_VERSION = RENDER_VERSION
