import type { ReactNode } from "react"
import { render } from "@testing-library/react"
import { PosteriumProvider } from "@/lib/context"
import type { PosteriumCtx } from "@/lib/context"
import { t } from "@/lib/i18n"
import { STREAMING_PLATFORMS } from "@/lib/utils"

function stubFn() {}
async function asyncStubFn() {}

export const MOCK_CTX: PosteriumCtx = {
  selected: null,
  setSelected: stubFn,
  view: "search",
  setView: stubFn,
  posters: [],
  loadingImages: false,
  previewPoster: null,
  setPreviewPoster: stubFn,
  selectedLogo: null,
  setSelectedLogo: stubFn,
  logos: [],
  posterActivePath: null,
  previewUrl: "",
  urlPattern: "",
  lang: "it",
  openSections: {},
  toggleSection: stubFn,
  posterScrollRef: { current: null },
  posterScrollInfo: { top: 0, height: 100 },
  setPosterScrollInfo: stubFn,
  selectPoster: asyncStubFn,
  selectLogo: asyncStubFn,
  removeLogo: asyncStubFn,
  logoBounds: { minX: -500, maxX: 500, minY: -500, maxY: 500 },
  logoScale: 75,
  setLogoScale: stubFn,
  logoOffsetX: 0,
  setLogoOffsetX: stubFn,
  logoOffsetY: 0,
  setLogoOffsetY: stubFn,
  backdrops: [],
  selectedBackdrop: null,
  setSelectedBackdrop: stubFn,
  backdropScale: 100,
  setBackdropScale: stubFn,
  backdropOffsetX: 0,
  setBackdropOffsetX: stubFn,
  backdropOffsetY: 0,
  setBackdropOffsetY: stubFn,
  selectBackdrop: stubFn,
  removeBackdrop: stubFn,
  editingValue: null,
  setEditingValue: stubFn,
  editText: "",
  setEditText: stubFn,
  globalBadges: false,
  setGlobalBadges: stubFn,
  rankingBadges: false,
  setRankingBadges: stubFn,
  customBadge: null,
  setCustomBadge: stubFn,
  gradientHeight: 30,
  setGradientHeight: stubFn,
  blurIntensity: 5,
  setBlurIntensity: stubFn,
  blurFade: 60,
  setBlurFade: stubFn,
  blurDarkness: 40,
  setBlurDarkness: stubFn,
  blurEnabled: false,
  setBlurEnabled: stubFn,
  badgeStyle: "shadow",
  setBadgeStyle: stubFn,
  defaultBadgeStyle: "shadow",
  setDefaultBadgeStyle: stubFn,
  defaultBlurEnabled: false,
  setDefaultBlurEnabled: stubFn,
  defaultBlurIntensity: 5,
  setDefaultBlurIntensity: stubFn,
  defaultBlurFade: 60,
  setDefaultBlurFade: stubFn,
  defaultBlurDarkness: 40,
  setDefaultBlurDarkness: stubFn,
  defaultGradientHeight: 30,
  setDefaultGradientHeight: stubFn,
  defaultGlobalBadges: false,
  setDefaultGlobalBadges: stubFn,
  defaultRankingBadges: false,
  setDefaultRankingBadges: stubFn,
  defaultAutoRotateClean: false,
  setDefaultAutoRotateClean: stubFn,
  defaultLogoFitEnabled: true,
  setDefaultLogoFitEnabled: stubFn,
  networkLogo: true,
  setNetworkLogo: stubFn,
  defaultNetworkLogo: true,
  setDefaultNetworkLogo: stubFn,
  trendRank: null,
  mdblistMatch: null,
  metaInfo: { genres: [], voteAverage: 0, awards: [], nominations: [], studios: [], franchise: null, basedOn: null, director: null },
  previewId: null,
  setPreviewId: stubFn,
  saveConfig: asyncStubFn,
  removeMapping: stubFn,
  mappingsMap: new Map(),
  goHome: stubFn,
  navigateToPoster: stubFn,
  refreshLists: asyncStubFn,
  tmdbKey: "test-key",
  setQuery: stubFn,
  doSearch: asyncStubFn,
  loadMore: asyncStubFn,
  titleOf: (r) => r.title || r.name || "",
  yearOf: (_r) => "",
  posterUrl: (path) => `https://image.tmdb.org/t/p/w500${path}`,
  trending: [],
  mdblistAnimeList: [],
  streamingCharts: {},
  STREAMING_PLATFORMS,
  loadMappings: asyncStubFn,
  query: "",
  results: [],
  searching: false,
  error: null,
  setError: stubFn,
  totalResults: 0,
  totalPages: 0,
  searchPage: 1,
  recentSearches: [],
  removeRecentSearch: stubFn,
  mappings: [],
  settingsRef: { current: null },
  langRef: { current: null },
  setLangOpen: stubFn,
  langOpen: false,
  pickLang: stubFn,
  settingsOpen: false,
  setSettingsOpen: stubFn,
  showLangPicker: false,
  setShowLangPicker: stubFn,
  t,
  tmdbKeyInput: "",
  setTmdbKeyInput: stubFn,
  showKey: false,
  setShowKey: stubFn,
  setTmdbKey: stubFn,
  mdblistApiKey: "",
  setMdblistApiKey: stubFn,
  exportData: asyncStubFn,
  importData: stubFn,
  copyUrl: asyncStubFn,
  copied: false,
  accentColor: "#555555",
  setAccentColor: stubFn,
  topEdgeColor: "#555555",
  rotationPosters: [],
  setRotationPosters: stubFn,
  autoRotateClean: false,
  setAutoRotateClean: stubFn,
  excludedPosters: [],
  setExcludedPosters: stubFn,
  logoDisabled: false,
  setLogoDisabled: stubFn,
  autoSaveExcludedPosters: asyncStubFn,
  theme: "dark",
  setTheme: stubFn,
  serviceErrors: {},
  setServiceErrors: stubFn,
  hasNetflixRank: false,
}

export function createWrapper(overrides?: Partial<PosteriumCtx>) {
  const ctx = { ...MOCK_CTX, ...overrides }
  return function Wrapper({ children }: { children: ReactNode }) {
    return <PosteriumProvider value={ctx}>{children}</PosteriumProvider>
  }
}

export function renderWithCtx(ui: ReactNode, overrides?: Partial<PosteriumCtx>) {
  return render(ui, { wrapper: createWrapper(overrides) })
}
