"use client"

/* eslint-disable @next/next/no-img-element -- badge previews are dynamic PNGs generated by the local API. */

import type { CSSProperties } from "react"
import { useP } from "@/lib/context"

const MIN_PREVIEW_W = 120

type BadgeStyle = "shadow" | "pill" | "bar" | "colored" | "default" | string | undefined

type RankingBadgeProps = {
  rank?: number | string
  label?: string
  topLight?: boolean
  containerW?: number
  badgeStyle?: BadgeStyle
  accentColor?: string
}

type GenreRatingBadgesProps = {
  genreName: string
  voteAverage: number
  containerW?: number
  containerH?: number
  bottomOffset?: number
  gradientHeight?: number
  blurIntensity?: number
  blurFade?: number
  blurDarkness?: number
  blurEnabled?: boolean
  badgeStyle?: BadgeStyle
  accentColor?: string
  topLight?: boolean
  releaseDate?: string | null
}

type ExtraBadgeProps = {
  label: string
  topLight?: boolean
  containerW?: number
  badgeStyle?: BadgeStyle
  accentColor?: string
}

function previewW(containerW: number): number {
  return Math.max(Math.round(containerW), MIN_PREVIEW_W)
}

function appendOptional(params: URLSearchParams, key: string, value: string | number | boolean | undefined | null): void {
  if (value === undefined || value === null || value === "") return
  params.set(key, String(value))
}

function appendTopLight(params: URLSearchParams, topLight?: boolean): void {
  if (topLight === undefined) return
  params.set("tl", topLight ? "1" : "0")
}

function badgePreviewUrl(params: URLSearchParams): string {
  return `/api/badge-preview?${params.toString()}`
}

function badgeImage(src: string, alt: string, style?: CSSProperties) {
  return (
    <img
      alt={alt}
      className="block select-none"
      decoding="async"
      draggable={false}
      src={src}
      style={style}
    />
  )
}

function rankingUrl({ rank = "13", label, topLight, containerW = 380, badgeStyle, accentColor }: RankingBadgeProps): string {
  const params = new URLSearchParams({
    kind: "ranking",
    pw: String(previewW(containerW)),
    rank: String(rank),
  })
  appendOptional(params, "label", label)
  appendOptional(params, "style", badgeStyle)
  appendOptional(params, "ac", accentColor)
  appendTopLight(params, topLight)
  return badgePreviewUrl(params)
}

function extraUrl({ label, topLight, containerW = 380, badgeStyle, accentColor }: ExtraBadgeProps): string {
  const params = new URLSearchParams({
    kind: "extra",
    pw: String(previewW(containerW)),
    label,
  })
  appendOptional(params, "style", badgeStyle)
  appendOptional(params, "ac", accentColor)
  appendTopLight(params, topLight)
  return badgePreviewUrl(params)
}

function genreUrl({ genreName, voteAverage, containerW = 380, badgeStyle, accentColor, topLight, releaseDate }: GenreRatingBadgesProps): string {
  const params = new URLSearchParams({
    kind: "genre",
    pw: String(previewW(containerW)),
    genre: genreName,
    vote: voteAverage.toFixed(1),
  })
  appendOptional(params, "year", releaseDate?.slice(0, 4))
  appendOptional(params, "style", badgeStyle)
  appendOptional(params, "ac", accentColor)
  appendTopLight(params, topLight)
  return badgePreviewUrl(params)
}

function RankingBadge({ rank = "13", label: labelProp, topLight, containerW = 380, badgeStyle, accentColor }: RankingBadgeProps) {
  const p = useP()
  const label = labelProp ?? p.t("ui.today") ?? "Oggi"
  const isBar = badgeStyle === "bar"
  const posStyle: CSSProperties = isBar
    ? { position: "absolute", top: 0, left: 0, right: 0, pointerEvents: "none" }
    : { position: "absolute", top: 0, left: "50%", transform: "translateX(-50%)", pointerEvents: "none" }
  const imageStyle: CSSProperties = isBar ? { width: "100%", height: "auto" } : { maxWidth: `${containerW - 20}px`, height: "auto" }
  const src = rankingUrl({ rank, label, topLight, containerW, badgeStyle, accentColor })

  return (
    <div style={posStyle} className="animate-fade-scale-in" key={badgeStyle}>
      {badgeImage(src, `#${rank} ${label}`, imageStyle)}
    </div>
  )
}

function GenreRatingBadges({
  genreName,
  voteAverage,
  containerW = 380,
  containerH = 570,
  bottomOffset = 0,
  gradientHeight = 30,
  blurIntensity = 5,
  blurFade = 60,
  blurDarkness = 40,
  blurEnabled = true,
  badgeStyle = "shadow",
  accentColor = "#000000",
  topLight,
  releaseDate,
}: GenreRatingBadgesProps) {
  const isBar = badgeStyle === "bar"
  const minH = Math.round(100 * containerH / 1500)
  const opaquePct = Math.max(100 - blurFade, 0)
  const targetCenter = 30 * containerH / 570 + bottomOffset
  const src = genreUrl({ genreName, voteAverage, containerW, badgeStyle, accentColor, topLight, releaseDate })
  const wrapperStyle: CSSProperties = isBar
    ? { animationDuration: "0.25s", position: "absolute", left: 0, right: 0, bottom: 0, pointerEvents: "none" }
    : {
      animationDuration: "0.25s",
      position: "absolute",
      width: "100%",
      bottom: `${Math.round(targetCenter)}px`,
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      transform: "translateY(50%)",
      zIndex: 10,
      pointerEvents: "none",
    }
  const imageStyle: CSSProperties = isBar ? { width: "100%", height: "auto" } : { maxWidth: `${containerW - 20}px`, height: "auto" }

  return (
    <>
      {blurEnabled && <div className="absolute bottom-0 left-0 right-0" style={{
        height: `${gradientHeight}%`,
        minHeight: `${minH}px`,
        backdropFilter: `blur(${blurIntensity}px)`,
        WebkitBackdropFilter: `blur(${blurIntensity}px)`,
        backgroundColor: `rgba(0,0,0,${blurDarkness / 100})`,
        maskImage: `linear-gradient(to top, black 0%, black ${opaquePct}%, transparent 100%)`,
        WebkitMaskImage: `linear-gradient(to top, black 0%, black ${opaquePct}%, transparent 100%)`,
        pointerEvents: "none",
      }} />}
      <div key={badgeStyle} className="animate-fade-scale-in" style={wrapperStyle}>
        {badgeImage(src, `${genreName} ${voteAverage.toFixed(1)}`, imageStyle)}
      </div>
    </>
  )
}

function ExtraBadge({ label, topLight, containerW = 380, badgeStyle, accentColor }: ExtraBadgeProps) {
  const isBar = badgeStyle === "bar"
  const posStyle: CSSProperties = isBar
    ? { position: "absolute", top: 0, left: 0, right: 0, pointerEvents: "none" }
    : { position: "absolute", top: 0, left: "50%", transform: "translateX(-50%)", pointerEvents: "none" }
  const imageStyle: CSSProperties = isBar ? { width: "100%", height: "auto" } : { maxWidth: `${containerW - 20}px`, height: "auto" }
  const src = extraUrl({ label, topLight, containerW, badgeStyle, accentColor })

  return (
    <div style={posStyle} className="animate-fade-scale-in" key={badgeStyle}>
      {badgeImage(src, label, imageStyle)}
    </div>
  )
}

export { RankingBadge, GenreRatingBadges, ExtraBadge }
